#!/usr/bin/env python3
"""
fetch_publications.py
─────────────────────
Reads PMIDs from scripts/pmids.txt, fetches metadata from the NCBI
PubMed API (no API key needed for small requests), and writes
_data/publications.yml for Jekyll to render.

Each publication entry includes an `author_names` list so that
member pages can filter publications by author name or ORCID.

Usage (from the repo root):
    python scripts/fetch_publications.py

Requirements:
    Python 3.8+  —  no extra packages needed (uses only stdlib)
"""

import json
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────
ROOT        = Path(__file__).parent.parent
PMIDS_FILE  = Path(__file__).parent / "pmids.txt"
OUTPUT_FILE = ROOT / "_data" / "publications.yml"

# ── NCBI E-utilities ───────────────────────────────────────────────────────
ESUMMARY_URL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
BATCH_SIZE   = 20
SLEEP_SEC    = 0.35


# ── Helpers ────────────────────────────────────────────────────────────────

def read_pmids(path):
    pmids, seen = [], set()
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if not line.isdigit():
            print(f"  [warn] Skipping non-numeric line: {line!r}", file=sys.stderr)
            continue
        if line not in seen:
            pmids.append(line)
            seen.add(line)
    return pmids


def fetch_summaries(pmids):
    results = {}
    for i in range(0, len(pmids), BATCH_SIZE):
        batch = pmids[i : i + BATCH_SIZE]
        params = urllib.parse.urlencode({
            "db":      "pubmed",
            "id":      ",".join(batch),
            "retmode": "json",
            "tool":    "igg-bioinfo-jekyll",
            "email":   "bioinfo@gaslini.org",
        })
        url = f"{ESUMMARY_URL}?{params}"
        print(f"  Fetching batch {i//BATCH_SIZE + 1}: PMIDs {batch[0]}...{batch[-1]}")
        try:
            with urllib.request.urlopen(url, timeout=15) as resp:
                data = json.loads(resp.read())
            results.update(data.get("result", {}))
        except urllib.error.URLError as exc:
            print(f"  [error] Network error: {exc}", file=sys.stderr)
            sys.exit(1)
        time.sleep(SLEEP_SEC)
    return results


def parse_authors(author_list):
    """Return (display_string, full_name_list).

    display_string  — truncated to 6 authors + 'et al.'
    full_name_list  — every author name, used for per-member filtering.
    """
    names = [a.get("name", "") for a in author_list if a.get("name")]
    display = ", ".join(names[:6]) + (", et al." if len(names) > 6 else "")
    return display, names


def parse_journal(summary):
    return summary.get("source", "")


def parse_volume_issue_pages(summary):
    vol   = summary.get("volume", "")
    issue = summary.get("issue", "")
    pages = summary.get("pages", "")
    parts = []
    if vol:
        parts.append(f"{vol}({issue})" if issue else vol)
    if pages:
        parts.append(f":{pages}")
    return "".join(parts)


def parse_doi(summary):
    for aid in summary.get("articleids", []):
        if aid.get("idtype") == "doi":
            return aid.get("value", "")
    return ""


def parse_year(summary):
    pub_date = summary.get("pubdate", "")
    if pub_date:
        return pub_date[:4]
    return summary.get("epubdate", "")[:4]


def qs(s):
    """Quote a string for YAML."""
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def build_yaml(pmids, summaries):
    lines = [
        "# Auto-generated by scripts/fetch_publications.py — do not edit by hand.",
        "# To update: edit scripts/pmids.txt then run the script again.",
        "",
        "publications:",
    ]

    def sort_key(pmid):
        s = summaries.get(pmid, {})
        return -int(parse_year(s) or 0)

    for pmid in sorted(pmids, key=sort_key):
        s = summaries.get(pmid)
        if s is None or s.get("error"):
            print(f"  [warn] PMID {pmid} not found in PubMed — skipping.", file=sys.stderr)
            continue

        title              = s.get("title", "").rstrip(".")
        authors_display, authors_list = parse_authors(s.get("authors", []))
        journal            = parse_journal(s)
        voliss             = parse_volume_issue_pages(s)
        doi                = parse_doi(s)
        year               = parse_year(s)
        pmid_id            = s.get("uid", pmid)

        lines += [
            f"  - pmid: {qs(pmid_id)}",
            f"    title: {qs(title)}",
            f"    authors: {qs(authors_display)}",
        ]

        # author_names: full list for member-page filtering
        lines.append("    author_names:")
        for name in authors_list:
            lines.append(f"      - {qs(name)}")

        lines.append(f"    journal: {qs(journal)}")
        if voliss:
            lines.append(f"    volume_issue_pages: {qs(voliss)}")
        if year:
            lines.append(f"    year: {qs(year)}")
        if doi:
            lines.append(f"    doi: {qs(doi)}")
        lines.append(f"    pubmed_url: \"https://pubmed.ncbi.nlm.nih.gov/{pmid_id}/\"")
        lines.append("")

    return "\n".join(lines)


# ── Main ───────────────────────────────────────────────────────────────────

def main():
    print("=== IGG Bioinfo Lab — PubMed publication fetcher ===\n")

    if not PMIDS_FILE.exists():
        print(f"[error] PMIDs file not found: {PMIDS_FILE}", file=sys.stderr)
        sys.exit(1)

    pmids = read_pmids(PMIDS_FILE)
    if not pmids:
        print("[warn] No PMIDs found in pmids.txt. Add some and try again.")
        sys.exit(0)

    print(f"Found {len(pmids)} PMID(s) to fetch.\n")

    summaries = fetch_summaries(pmids)
    summaries.pop("uids", None)

    yaml_content = build_yaml(pmids, summaries)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(yaml_content, encoding="utf-8")

    print(f"\n Written to {OUTPUT_FILE.relative_to(ROOT)}")
    print("  Commit both scripts/pmids.txt and _data/publications.yml.")


if __name__ == "__main__":
    main()
